# Generated by Django 5.2.13 on 2026-04-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_appointment_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
