# Generated by Django 5.2.13 on 2026-04-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_appointment_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('pediatrics', 'Pediatrics'), ('general', 'General Physician'), ('dentist', 'bds')], max_length=100),
        ),
    ]
